- block:
  - name: "Load user class variables"
    include_vars: "{{ class }}.yml"

  - name: "Add groups for class {{ class }}"
    group:
      name: "{{ item.key }}"
      state: "{{ item.value.state | default('present') }}"
      gid: "{{ item.value.gid }}"
    with_dict: "{{ GROUPS }}"

  - name: "Set up sudo access"
    lineinfile:
      dest: /etc/sudoers
      regexp: '^%{{ item.key }}'
      line: '%{{ item.key }} ALL=(ALL) NOPASSWD: ALL'
      state: "{% if item.value.sudo | default(False) | bool() %}present{% else %}absent{% endif %}"
    with_dict: "{{ GROUPS }}"

  - include: user_tasks.yml ENTRIES={{ USERS }}
  when: class != "local" 

- block:
  - name: "Add local groups"
    group: name={{ item }} state={{ LOCAL_GROUPS[item] }}
    with_items: "{{ LOCAL_GROUPS|default([])|list }}"

  - name: "Add local users"
    include: user_tasks.yml ENTRIES={{ LOCAL_USERS|default([]) }}
    when: LOCAL_USERS is defined
  when: class == "local"

