---

- name: Apt-pin ansible
  template:
    src: ansible.pref.j2
    dest: /etc/apt/preferences.d/ansible.pref

- name: Ensure Ansible is installed
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - "ansible={{ ansible_pin_version }}"

- name: "Delete Ansible 1.0 plugin dir"
  file: path=/usr/share/ansible_plugins state=absent

- name: "Create callback plugin dir"
  file: path={{ item }} state=directory
  with_items:
    - /usr/share/ansible/plugins
    - /usr/share/ansible/plugins/callback

- name: "Install callback module"
  template: src=ring_callback.py.j2 dest=/usr/share/ansible/plugins/callback/ring.py

- name: Ensure Ansible cronjob exists
  template:
    src: cron.d/ansible.j2
    dest: /etc/cron.d/ansible

- name: "Delete ansible.j2 (temp)"
  file: path=/etc/cron.d/ansible.j2 state=absent

- name: Remove any old ansible crontab entries
  lineinfile:
    dest: /var/spool/cron/crontabs/root
    regexp: 'ansible(-|_)pull'
    state: absent

- name: Remove any old salt crontab entries
  lineinfile:
    dest: /var/spool/cron/crontabs/root
    regexp: 'salt-call'
    state: absent

